'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VehicleInfoDisplay
    
    '''<summary>
    '''spn_Heading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_Heading As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''img_Thumbnail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_Thumbnail As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''spn_Engine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_Engine As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spn_Trans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_Trans As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spn_Mileage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_Mileage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spn_ExtColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_ExtColor As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spn_IntColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_IntColor As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spn_VIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_VIN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spn_Price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_Price As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spn_CityEconomy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_CityEconomy As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spn_HwyEconomy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn_HwyEconomy As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
