'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SAAutosMasterPage
    
    '''<summary>
    '''frm_SAAutosForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_SAAutosForm As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''cph_MainPageContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cph_MainPageContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
